
CREATE TABLE IF NOT EXISTS roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name     VARCHAR(256)                            NOT NULL,
    user_password VARCHAR(128)                            NOT NULL,
    email         VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS message
(
    message_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id   BIGINT                                  NOT NULL, --отправитель
    receiver_id BIGINT                                  NOT NULL, --получатель
    text        TEXT                                    NOT NULL,
    CONSTRAINT message_user_1 FOREIGN KEY (sender_id) REFERENCES USERS ON DELETE CASCADE,
    CONSTRAINT message_user_2 FOREIGN KEY (receiver_id) REFERENCES USERS ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscribers
(
    sender_id     BIGINT NOT NULL, --пользователь
    subscriber_id BIGINT NOT NULL, --подписчик
    CONSTRAINT subscriber PRIMARY KEY (sender_id, subscriber_id),
    CONSTRAINT message_user_1 FOREIGN KEY (sender_id) REFERENCES USERS ON DELETE CASCADE,
    CONSTRAINT message_user_2 FOREIGN KEY (subscriber_id) REFERENCES USERS ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   BIGINT not null,
    friend_id BIGINT not null,
    CONSTRAINT friendship PRIMARY KEY (user_id, friend_id),
    CONSTRAINT friendship_user_1 FOREIGN KEY (user_id) REFERENCES USERS ON DELETE CASCADE,
    CONSTRAINT friendship_user_2 FOREIGN KEY (friend_id) REFERENCES USERS ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends_request
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    receiver_id BIGINT                                  NOT NULL, --пользователь
    sender_id   BIGINT                                  NOT NULL, --отправитель
    CONSTRAINT message_user_1 FOREIGN KEY (sender_id) REFERENCES USERS ON DELETE CASCADE,
    CONSTRAINT message_user_2 FOREIGN KEY (receiver_id) REFERENCES USERS ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_role_id_users_roles FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT fk_user_id_users_roles FOREIGN KEY (user_id) REFERENCES users (user_id)
);
